### ISSUE TITLE
No marshaller registered for object of Java

### ISSUE THREAD

**Issue by amoAHCP** [infinispan/infinispan-simple-tutorials#121]
Running your example: https://github.com/infinispan/infinispan-simple-tutorials/tree/master/spring-integration/spring-boot/remote with the latest infinispan release (12.1.3.final). Results in following Exception:

java.lang.IllegalArgumentException: No marshaller registered for object of Java type org.infinispan.tutorial.simple.spring.remote.BasqueName : BasqueName{id=6, name='Koldo'}
	at org.infinispan.protostream.impl.SerializationContextImpl.getMarshallerDelegate(SerializationContextImpl.java:512) ~[protostream-4.4.0.Final.jar:4.4.0.Final]

The error seems to occur while deserialization, since  I can see the Entries in the Server. A (quick) Debugging in SerializationContextImpl indicates that class BasqueName neither is present in marshallersByClass nor in legacyMarshallerProviders.

Using the org.infinispan.commons.marshall.JavaSerializationMarshaller works fine.

**Comment by karesti** [comment]
@amoAHCP  thanks, there was a not expected commit changing the marshaller! Thanks, I'm fixing the tutorial to move it to protostream completely
