### ISSUE TITLE
Dockerize the demos

### ISSUE THREAD

**Issue by gustavonalle** [infinispan/infinispan-simple-tutorials#38]
A handful of tutorials require an external server to be running, ideally the samples should start docker containers for that, similarly to the ```spark/``` demo

**Comment by karesti** [comment]
@gustavonalle

**Comment by karesti** [comment]
@gustavonalle have you seen this ? https://github.com/dnno/testcontainers-infinispan

**Comment by gustavonalle** [comment]
No @karesti, do you think it could be used in the simple tutorial? How?

**Comment by karesti** [comment]
maybe creating an standalone infinispan server programmatically and containers

**Comment by karesti** [comment]
for the client/server examples

**Comment by gustavonalle** [comment]
Sound an interesting option. But not sure how up-to-date that library would be, since we usually change the tutorials minutes after a release :)
What am doing in the Spark tutorial is manually launching the container for infinispan and spark in a [script](https://github.com/infinispan/infinispan-simple-tutorials/blob/master/spark/script.sh), maybe for the others modules, maven can launch before running
